AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  HereApiKey:
    Type: String
    Description: HERE Location Services API Key (https://developer.here.com/faqs#access-control)

Resources:
  TransitFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs12.x
      Handler: transit.transitGET
      Description: 'A Lambda function to get access to features that go beyond simple estimated transit routing like search, next departures, transit isoline and pedestrian access points.'
      Environment:
        Variables:
          HERE_API_KEY: !Ref HereApiKey
      Events:
        GET:
          Type: Api
          Properties:
            Path: /transit/api/{resourcePath+}
            Method: get
Outputs:
  HereApiURL:
    Description: "AWS API Gateway URL for HERE Public Transit API."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"