AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  HereAppId:
    Type: String
    Description: HERE Location Services API App ID (https://saas.awsmarketplace.here.com/faq#api-access)
  HereAppCode:
    Type: String
    Description: HERE Location Services API App Code (https://saas.awsmarketplace.here.com/faq#api-access)

Resources:
  TransitFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs8.10
      Handler: transit.transitGET
      Description: 'A Lambda function to get access to features that go beyond simple estimated transit routing like search, next departures, transit isoline and pedestrian access points.'
      Environment:
        Variables:
          HERE_APP_ID: !Ref HereAppId
          HERE_APP_CODE: !Ref HereAppCode
      Events:
        GET:
          Type: Api
          Properties:
            Path: /transit
            Method: get
Outputs:
  HereApiURL:
    Description: "AWS API Gateway URL for HERE Public Transit API."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"