AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  HereAppId:
    Type: String
    Description: HERE Location Services API App ID (https://saas.awsmarketplace.here.com/faq#api-access)
  HereAppCode:
    Type: String
    Description: HERE Location Services API App Code (https://saas.awsmarketplace.here.com/faq#api-access)

Resources:
  PlacesFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs8.10
      Handler: places.placesGET
      Description: 'A lambda function to find (e.g., search for name, type, category), discover (e.g., look into address, contact info) and interact with POI information (e.g., enable user reviews, photos).'
      Environment:
        Variables:
          HERE_APP_ID: !Ref HereAppId
          HERE_APP_CODE: !Ref HereAppCode
      Events:
        GET:
          Type: Api
          Properties:
            Path: /places
            Method: get
Outputs:
  HereApiURL:
    Description: "AWS API Gateway URL for HERE Places API."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"