AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  HereApiKey:
    Type: String
    Description: HERE Location Services API Key (https://developer.here.com/faqs#access-control)

Resources:
  WeatherFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: nodejs12.x
      Handler: weather.weatherGET
      Description: 'A lambda function to give insights into real-time weather forecasts, alerts, and astronomical info for any location.'
      Environment:
        Variables:
          HERE_API_KEY: !Ref HereApiKey
      Events:
        GET:
          Type: Api
          Properties:
            Path: /weather/api/{resourcePath+}
            Method: get
Outputs:
  HereApiURL:
    Description: "AWS API Gateway URL for HERE Weather API."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"